matrix:
  include:
    - language: cpp
      addons:
        apt:
          packages:
            - libxerces-c-dev
            - valgrind
            
      script:
        - mkdir regxmllib/build
        - cd regxmllib/build
        - cmake ..
        - cmake --build .
        - ctest .
        - ctest -T memcheck .
        - sudo make install
      
    - language: java
      install:
        - sudo apt-get install junit
        - sudo apt-get install libhamcrest-java
      script:
        - cd regxmllib
        - ant -Dbuild.sysclasspath=first test